### ISSUE TITLE
Annotationview text scaling

### ISSUE THREAD

**Issue by TripwireNL** [almassapargali/LocationPicker#10]
Hi,

I'm trying to localize the text used in the AnnotationView. I saw you updated the view a few days ago and now we can set the selectButtonTitle of the AnnotationView. Is there a way to make the AnnotationView larger when the selectButtonTitle text is larger than normal? For instance Select is in Dutch Selecteer which doesn't fit right now in the AnnotationView.

Thx!

**Comment by almassapargali** [comment]
Hello, sorry for really late response, I've changed it to grow dynamically to fit label.

**Comment by TripwireNL** [comment]
Hi, Thanks for the fixing :) Can you make a new Cocoapods release? I tried updating but it's still version 0.55 on Cocoapods! Thanks again for the fix!

**Comment by almassapargali** [comment]
Check it now, I've updated!

**Comment by TripwireNL** [comment]
Great it's working perfectly!
