### ISSUE TITLE
Publish as LocationPicker

### ISSUE THREAD

**Issue by jcampbell05** [almassapargali/LocationPicker#15]
It would be helpful if you published the spec as the same name as the package manager.

**Comment by almassapargali** [comment]
I'm sorry, could be please give more details? Which spec to which package manager?

**Comment by jcampbell05** [comment]
Just to have the podspec name to be LocationPicker rather than LocationPickerViewController

**Comment by almassapargali** [comment]
Isn't pod spec name LocationPicker already?

**Comment by jcampbell05** [comment]
No it appears to be "LocationPickerViewController"

**Comment by almassapargali** [comment]
Please check again, that should be another library. How are you checking, btw?

**Comment by jcampbell05** [comment]
I looked into the Cocoapod Repo as I used Location Picker and the code in your examples wasn't compiling. It seems like in the master repo the later versions are called LocationPickerViewController
