### ISSUE TITLE
Ask for permissions if needed

### ISSUE THREAD

**Issue by vladvelici** [almassapargali/LocationPicker#21]
This picker is idea for apps that don't use location and maps too much, therefore dealing with location permissions would be ideal. At least for my use case.

I could implement it and send a pull request in the following few days if this sounds like something important.

This can be a configurable feature, like `locationPicker.askForPermission`, and can take three values `.No`, `.WhenInUse`, `.Always`, so the app developers can choose what level of permission to ask for, just in case they use location in different parts of the app.

What do you think?

**Comment by almassapargali** [comment]
Sounds interesting, but the thing is, user's location actually isn't needed to pick location. The only case when it's needed, is when we show user's location initially.

**Comment by almassapargali** [comment]
Btw, if you think that this would be helpful, and that resulting code would be small enough, then go ahead, and implement it. Please make sure that we ask for permission only if we need it (like when `showCurrentLocationInitially` or `showCurrentLocationButton` is true). I'll review and merge.
