### ISSUE TITLE
open LocationPickerViewController

### ISSUE THREAD

**Issue by AlexZd** [almassapargali/LocationPicker#25]
Now it is `public`, in this case I can't inherit it, better to use `open`

**Comment by almassapargali** [comment]
It's made 'public' intentionally, it's not meant to be subclasses. What are you trying to achieve by subclassing?

**Comment by AlexZd** [comment]
Need to make some additional setting in `viewDidLoad` and `viewWillAppear`

**Comment by TripwireNL** [comment]
I'd like to have it open as well since I use your controller in Eureka forms to make a custom LocationPicker row

**Comment by almassapargali** [comment]
Ok guys, it's open now, please use version `1.0.2`.
