### ISSUE TITLE
Select current location

### ISSUE THREAD

**Issue by Parkyprg** [almassapargali/LocationPicker#26]
Hi, 

Nice work with this picker.
However, I use it in Obj-C project and I want the user to be able to select the current location.
If I press on the standard locate button, the location is not selectable. 

How can I do it in your code, using swift? The pin should be added on the current user location.

Thanks.

**Comment by Parkyprg** [comment]
Awesome support. 2 weeks without a single response. Thank you!

**Comment by PaulRBerg** [comment]
+1

**Comment by PaulRBerg** [comment]
@Parkyprg 
UPDATE

I've solved the bug. I assume you've tested on your simulator, just like me. I've put the following function in the project:

```
public func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
        print("error: %@", error.localizedDescription)
     }
```

And apparently I was receiving a **KCLErrorDomain error 0**.
Check out a solution for you [here](http://stackoverflow.com/questions/1409141/location-manager-error-kclerrordomain-error-0).

In my case, I just had to select "None" Then "Current Location" again.
Hope it helps you or anyone.

Thanks @almassapargali for this simple but amazing library!

**Comment by almassapargali** [comment]
Hello @Parkyprg, @razvan-paul sorry guys, yes I know that picking user's current location would be a great feature to add, and very useful, but unfortunately I don't have much available time currently, so feel free to send any PRs, would happily review and merge them.

**Comment by almassapargali** [comment]
Made long press gesture work on current location blue dot too. Sorry for delay!
