### ISSUE TITLE
Missing argument for parameter 'placemark' in call

### ISSUE THREAD

**Issue by alleyrat** [almassapargali/LocationPicker#27]
The sample posted no longer compiles with xCode 8.1 and Swift 3.

The problem lies on the line:
let initialLocation = Location(name: "my home", location: location)

"Missing argument for parameter 'placemark' in call". The compiler wants:
let initialLocation = Location(name: "my home", location: location, placemark: placemark)

I've been trying to understand how to init CLPlacemark from CLLocation, but I've had no luck. 

I can not get xCode to recognize init(location: CLLocation, name: String?, postalAddress: CNPostalAddress?) so I do not have an easy way to create a CLPlacemark from CLLocation.

If I pass in an empty CLPlacemark, it crashes.

**Comment by almassapargali** [comment]
Hello, sorry, away from Mac now. Could you please try with MKPlacemark, passing [:] as address dictionary?
