### ISSUE TITLE
Localization question

### ISSUE THREAD

**Issue by guillotemanija** [almassapargali/LocationPicker#28]
Hi there, very nice tool.

Is it possible to localize all aspects of this location picker? This would include not only the searchBarPlaceholder and the searchHistoryLabel, but also the Back button, the Cancel button, the Select button and the language of the addresses?

Thank you

**Comment by almassapargali** [comment]
Hello, `Select` button is public variable, as for back, system button/localization gets used there. And language of addresses is based on where address is located AFAIK. You can look [here](https://developer.apple.com/reference/mapkit/mklocalsearch) for information on location search.
