### ISSUE TITLE
Question: is there any way to use your library to get list of cities and countries

### ISSUE THREAD

**Issue by oferRounds** [almassapargali/LocationPicker#3]
i.e., without asking for user's location permission and without presenting the user's location on map.
Just let him type city/country with autocomplete suggestions.

Thanks for sharing this library!

**Comment by almassapargali** [comment]
Nope, sorry. It shows map always. You should take a look at `MKLocalSearchRequest`.

**Comment by oferRounds** [comment]
Cool, thanks for your answer!
