### ISSUE TITLE
tap to change pin location

### ISSUE THREAD

**Issue by sleith** [almassapargali/LocationPicker#33]
Hi sir,
would it possible to add option so that on tap to change the current location?
currently long tap will do it, but most of user might don't know this.
Because this is location picker, so this option would be very helpful i think.
(i test android lib https://github.com/SchibstedSpain/Leku, which does this)

thanks :)

**Comment by almassapargali** [comment]
Hello, I've followed pattern used in Apple Maps and Google Maps.
