### ISSUE TITLE
Can't import LocationPicker module

### ISSUE THREAD

**Issue by jboss42** [almassapargali/LocationPicker#35]
I installed LocationPicker module using pod.
But can't import module. (Xcode 8.3, Swift 3.0)

**Comment by karuppasamypandian0856** [comment]
hi cant import as module, so i have added that project then can run in simulator but cant run in device.cant launch the app.
Worked on xcode 8.3 and swift 3

![screen shot 2017-09-22 at 7 53 13 pm](https://user-images.githubusercontent.com/19841870/30749389-dd95fe70-9fd0-11e7-8cc7-e65fff127982.png)

Any one face this problem?

**Comment by karuppasamypandian0856** [comment]
Finally the error was the PRODUCT_BUNDLE_IDENTIFIER field in the info.plist of each pod. Changing it to "org.cocoapods.${PRODUCT_NAME:rfc1034identifier}" solved the problem (previously was "$(PRODUCT_BUNDLE_IDENTIFIER)").
