### ISSUE TITLE
select the current location initialy

### ISSUE THREAD

**Issue by almatri** [almassapargali/LocationPicker#36]
How can I select the current location when initialy after opening the map, because currently it only shows the current location and the user may think it is already selected or even when the user tap the current location circle it does nothing and the user still has to tap long to select the locatoin

**Comment by seifeet** [comment]
Seems like it is already implemented and works fine on a physical device.

        // button placed on right bottom corner
        locationPicker.showCurrentLocationButton = true // default: true
        
        // ignored if initial location is given, shows that location instead
        locationPicker.showCurrentLocationInitially = true // default: true

**Comment by almassapargali** [comment]
Oh, I somehow missed this issue, and just see it after email for @seifeet's comment. Yes, currently it just shows current location, and doesn't selects it. Please see #32 for behavior you want, and comments.

**Comment by almassapargali** [comment]
Added `selectCurrentLocationInitially`, will release in `1.1.0` soon.
