### ISSUE TITLE
The following binaries use incompatible versions of Swift:in Xcode9

### ISSUE THREAD

**Issue by karuppasamypandian0856** [almassapargali/LocationPicker#37]
Its not support in xcode 9?

**Comment by NikKovIos** [comment]
Fix some issues with swift 4 and Xcode 9 please.

**Comment by karuppasamypandian0856** [comment]
Thank you for answering this.
All issues and warnings are converted to swift4.But still issue there
Note : We are manually integrated this framework.

**Comment by NikKovIos** [comment]
Also there is a bug with the navigation bar when pushing this controller after popping it back

**Comment by jackpaster** [comment]
@almassapargali Can you fix this issue on the iPhone x. There is an issue when going back and id like to get that fixed. when going back in a navigation controller. the location search bar stalls. @NikKovIos @karuppasamypandian0856 Have any of you created a fix to this problem.

**Comment by NikKovIos** [comment]
No, i used another pod

**Comment by jackpaster** [comment]
@NikKovIos can you share what pod you used. it would be helpful as this pod isn't being updated

**Comment by almassapargali** [comment]
Hello, guys, sorry for being unresponsive, quite a busy nowadays. I've spent couple of hours trying to fix that thing today, but no avail. Tried to wrap UISearchBar in UIView so it disappears correctly, though couldn't work out layouts. Will take an another look when I get more time. Feel free to PR if anyone has any success fixing that.

**Comment by jackpaster** [comment]
@almassapargali Have you come up with a solution. I'm looking to update my app in the App Store by the end of next week. Should I use a different repository. I just need to know because down time is everything. Thanks and hope to hear back from you.

**Comment by NikKovIos** [comment]
@jackpaster `pod 'LocationPickerViewController'`

**Comment by almassapargali** [comment]
Will publish `1.1.0` now. Sorry for delay.
