### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by lightsprint09** [almassapargali/LocationPicker#40]
![simulator screen shot - iphone se - 2018-01-04 at 17 13 42](https://user-images.githubusercontent.com/3703083/34572861-c49b4d00-f172-11e7-8d02-06fb3b12c9f0.png)
![simulator screen shot - iphone se - 2018-01-04 at 17 13 50](https://user-images.githubusercontent.com/3703083/34572866-c87988e2-f172-11e7-9530-a39d3522fdd0.png)

I push the LocationPicker into a NavigationController

**Comment by gkye** [comment]
If you're on iOS 11 this should fix it:
```swift
    if #available(iOS 11.0, *) {
      search.searchBar.heightAnchor.constraint(equalToConstant: 44).isActive = true
    }
```

**Comment by almassapargali** [comment]
Sorry, couldn't reproduce issue, could you please make a demo project.

**Comment by tharak** [comment]
same problem here, just copied and pasted the sample from README.md inside the button event
my deployment target is 9.0

**Comment by weakfl** [comment]
If you really want to have the searchBar inside the navigationBar on iOS 11 you could fix the issue like this:
```swift
extendedLayoutIncludesOpaqueBars = true
```

However, I'd suggest to do it iOS 11 style, so here's a PR fixing the issue: #46
