### ISSUE TITLE
Localizing searchBarPlaceholder

### ISSUE THREAD

**Issue by tharak** [almassapargali/LocationPicker#44]
changing searchBarPlaceholder is changing its value but not the searchbar placeholder value
i think this fix it

LocationPickerViewController
/// default: "Search or enter an address"
    public var searchBarPlaceholder : String = "Search or enter an address" {
        didSet{
            searchBar.placeholder = self.searchBarPlaceholder
        }
    }

**Comment by weakfl** [comment]
@tharak Closing, as this issue is rather old.

The searchBar placeholder should be set before presenting the location picker. If  you really need to change the placeholder on the fly please reopen and explain your use case in detail.
