### ISSUE TITLE
Version 1.3.0 not available on cocoapods

### ISSUE THREAD

**Issue by weakfl** [almassapargali/LocationPicker#49]
Version 1.3.0 does not propagate to cocoapods, see [last release](https://cocoapods.org/pods/LocationPicker).

Did you `pod lib lint` the latest version? Maybe it fails because the `.swift-version` still says `3.0`?
Whatever the reason is, the update is not available...

**Comment by weakfl** [comment]
I've submitted a PR (#50).

**Comment by weakfl** [comment]
Thanks for merging @almassapargali, but I think you still need to move the `1.3.0` tag to the latest commit and push the podspec.

**Comment by weakfl** [comment]
@almassapargali bump

**Comment by blinkuz** [comment]
The latest version is not yet available in cocoapods

**Comment by weakfl** [comment]
@almassapargali Could you please move the `1.3.0` tag to the latest commit and push the version to cocoapods?

I'd like to provide a PR for Swift 5, but I think it would make sense to release `v1.3.0` first...
