### ISSUE TITLE
Undefined behavior error for UISearchController

### ISSUE THREAD

**Issue by bharatkrishna** [almassapargali/LocationPicker#5]
In my project I have a Table View Controller embedded in a Navigation Controller. I am launching the LocationPickerViewController via a button in the navigation bar. 
Sometimes when I don't select any location and go back to the previous screen and again come to the Location Picker scene the following error is printed to the console:

> Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<UISearchController: 0x14a851f90>)

Searching the web, I found [this](http://stackoverflow.com/a/33589770/317512) stackoverflow answer which recommended to call the loadViewIfNeeded() method of the UISearchController in the class' deinit.
I added it as follows in LocationPickerViewController:

``` swift
    deinit {
        searchTimer?.invalidate()
        localSearch?.cancel()
        geocoder.cancelGeocode()
        searchController.loadViewIfNeeded() // Added call to loadViewIfNeeded() 
    }
```

The error does not appear anymore after this. Maybe this call to loadViewIfNeeded() needs to be added.

**Comment by almassapargali** [comment]
Thanks for reporting, closed by 13c8a7a6e91adc20d89786757082b01ceb202cb1.
