### ISSUE TITLE
location bounds

### ISSUE THREAD

**Issue by Marchuck** [almassapargali/LocationPicker#51]
Hello all!
Thanks for amazing LocationPicker, this library helped me a lot!
I am curious if there's possibility to set latitude / longitude bounds (like Android's `LatLngBounds`)
for ViewController (`northeast` and `southwest` coordinates I guess)

**Comment by weakfl** [comment]
You can set a preferred distance, if that's what you mean:

```swift
// optional region distance to be used for creation region when user selects place from search results
locationPicker.resultRegionDistance = 500 // default: 600
```
