### ISSUE TITLE
modally present this LocationPicker

### ISSUE THREAD

**Issue by fitsyu** [almassapargali/LocationPicker#53]
Thanks for a great and useful component.
In my case, I have to be able to show this component any where independent of any navigation sequence. So being able to show it modally is important. However this component seems to be designed to work with UINavigationController.

So here is how currently do it.

```
 @objc func openLocationPicker() {
        
        // setup the location picker
        let locationPicker = LocationPickerViewController()
         
        // add cancel button to dismiss it
        locationPicker.navigationItem.leftBarButtonItem =
            UIBarButtonItem(title: "Cancel", style: .plain, target: self, action: #selector(closeLocationPicker))
        
        // set the wrapper
        let nc = UINavigationController(rootViewController: locationPicker)
        
        // show it modally
        UIApplication.shared
            .topViewController()?
            .present(nc, animated: true, completion: {})
    }
    
    // dismiss the modally presented LocationPicker
    @objc func closeLocationPicker() {
        UIApplication.shared
            .topViewController()?
            .presentedViewController?.dismiss(animated: true, completion: nil)
    }
```

Hope this can be useful for others who got in situation like this.
Thanks!

**Comment by fury21** [comment]
Not work, try this code:


 @IBAction func btn(_ sender: Any) {
     // setup the location picker
        let locationPicker = LocationPickerViewController()
         
        // add cancel button to dismiss it
        locationPicker.navigationItem.leftBarButtonItem =
            UIBarButtonItem(title: "Cancel", style: .plain, target: self, action: #selector(closeLocationPicker))
        
        // set the wrapper
        let nc = UINavigationController(rootViewController: locationPicker)
        
        // show it modally
        self.present(nc, animated: true, completion: nil)

    }
    
    // dismiss the modally presented LocationPicker
    @objc func closeLocationPicker() {
        self.dismiss(animated: true, completion: nil)
    }
