### ISSUE TITLE
Print Location (Latitute and longitude)

### ISSUE THREAD

**Issue by agentelu** [almassapargali/LocationPicker#56]
Hi, how can a print de location (Latitude and longitude) when i pick a and select a new location ?

**Comment by naveedmcs** [comment]
locationPicker.completion = { location in
            self.lat = location?.coordinate.latitude ?? 0.0
            self.long = location?.coordinate.longitude ?? 0.0
            self.txtaddress.text = location?.address ?? "address not found"
        }
