### ISSUE TITLE
how to get placeMark object ? 

### ISSUE THREAD

**Issue by naveedmcs** [almassapargali/LocationPicker#58]
I want to selected last selected location from map but I have only address string and coordinates for location constructor, placeMark paramter ? can you please remove it ? or fix to stop crashing

let initialLocation = Location(name: "My home", location: location, placeMark: CLPlaceMark )

**Comment by weakfl** [comment]
@nvdmcs Just use an `MKPlacemark` instead:

```swift
let placemark = MKPlacemark(coordinate: CLLocationCoordinate2D(latitude: 37.331686, longitude: -122.030656), addressDictionary: nil)
let location = Location(name: "1 Infinite Loop, Cupertino", location: nil, placemark: placemark)
locationPicker.location = location
```
