### ISSUE TITLE
current location not working

### ISSUE THREAD

**Issue by naveedmcs** [almassapargali/LocationPicker#59]
selectCurrentLocationInitially is set true but when i tapped on right bottom icon for current location , there is no marker and map is not updating for current location

here is my code 
 let locationPicker = LocationPickerViewController()
 
        locationPicker.location = location
        locationPicker.searchBarStyle = .prominent
        locationPicker.mapType = .standard
        locationPicker.showCurrentLocationButton = true
        locationPicker.useCurrentLocationAsHint = true
        locationPicker.selectCurrentLocationInitially = true
       
        locationPicker.completion = { location in
            self.lat = location?.coordinate.latitude ?? 0.0
            self.long = location?.coordinate.longitude ?? 0.0
            self.txtaddress.text = location?.address ?? "--"
        }
        navigationController?.pushViewController(locationPicker, animated: true)

**Comment by weakfl** [comment]
If the `location` property is set, `selectCurrentLocationInitially` is ignored:

https://github.com/almassapargali/LocationPicker/blob/907f51465d7511b7c7661977d7e5bbd162c50f4f/LocationPicker/LocationPickerViewController.swift#L190-L207
