### ISSUE TITLE
APIs deprecated for iOS 9

### ISSUE THREAD

**Issue by bharatkrishna** [almassapargali/LocationPicker#6]
xCode throws method deprecation warnings when Deployment Target is set to 9.2

> LocationPicker/LocationPicker/Location.swift:30:12: 'ABCreateStringWithAddressDictionary' was deprecated in iOS 9.0: Use CNPostalAddressFormatter from Contacts.framework instead
> 
> LocationPicker/LocationPicker/LocationPickerViewController.swift:325:7: 'pinColor' was deprecated in iOS 9.0: Use pinTintColor instead

**Comment by almassapargali** [comment]
I'm planning to support iOS 8 at least until iOS 10 rolls out, so will keep these as is for now.
