### ISSUE TITLE
Cannot form weak reference to instance (0x7ff94e02a000) of class LocationPicker.LocationPickerViewController. It is possible that this object was over-released, or is in the process of deallocation

### ISSUE THREAD

**Issue by merovic** [almassapargali/LocationPicker#61]
Error Happen After Latest Xcode Update when initiating LocationPickerViewController

**Comment by weakfl** [comment]
@merovic please provide details of your implementation and steps to reproduce this issue.

**Comment by merovic** [comment]
I only starts to initialize LocationPickerViewController like ( let picker = LocationPickerViewController ) and then starts to follow the sample code like the readme file and everything was okay until recent update to Xcode and it is no longer working and this error emerges 
<img width="571" alt="Screen Shot 2019-11-03 at 11 41 23 PM" src="https://user-images.githubusercontent.com/11374760/68092414-764e4780-fe93-11e9-9e47-cdc9f5ecfce3.png">

**Comment by weakfl** [comment]
I can't reproduce this with the demo app using Xcode 11.2. Please provide more details of your usage.

**Comment by merovic** [comment]
I used it before many times and everything works as expected until yesterday everything stopped working and that error emerges, I tried to use it manually instead of cocoa pods but the same error too, error emerges directly even if I just initialized the controller without any usage
<img width="759" alt="Screen Shot 2019-11-04 at 10 03 39 AM" src="https://user-images.githubusercontent.com/11374760/68106447-5ac25b80-feea-11e9-8abe-1f1612756091.png">

**Comment by merovic** [comment]
try to use the library using cocapods in a new project in order to reproduce the error

**Comment by weakfl** [comment]
@merovic Please provide a sample project, thanks.

**Comment by merovic** [comment]
[TestLocationPicker.zip](https://github.com/almassapargali/LocationPicker/files/3804007/TestLocationPicker.zip)

**Comment by weakfl** [comment]
Thanks @merovic, fixed in [1.4.2](https://github.com/almassapargali/LocationPicker/tree/1.4.2).

**Comment by Fayis2021** [comment]
erro

**Comment by Fayis2021** [comment]
Error -- Xcode build done.       
Failed to build iOS app
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
../ios/Pods/LocationPicker/LocationPicker/LocationPickerViewController.swift:59:5
xcode 15.3
