### ISSUE TITLE
Title disappears

### ISSUE THREAD

**Issue by fury21** [almassapargali/LocationPicker#63]
Hi! Why title disappears, immediately after the appears of?
Look my video

![BAADAgADIgUAAvYu4Ep30C4reCzrkhYE_1574700403 4](https://user-images.githubusercontent.com/30409500/69560242-818d2280-0fbc-11ea-8af4-f9499aa53899.gif)

**Comment by weakfl** [comment]
Please provide more details about your implementation. Ideally with steps to reproduce this issue.

**Comment by fury21** [comment]
@objc private func touchToSelectAddressLabel() {
        hideKeyboardGesture()
        
      // setup the location picker
        
         
        locationPicker.mapType = .standard // default: .Hybrid
        locationPicker.searchBarPlaceholder = "Поиск по адресу" // default: "Search or enter an address"
        locationPicker.searchHistoryLabel = "История поиска" // default: "Search History"
        locationPicker.selectButtonTitle = "Выбрать"
        
        locationPicker.completion = { location in
            self.addressVpsika = location!.address
            self.coordinatesVpiska = location?.coordinate
            
            self.addressLabel.text = location!.address
        }
        
        // add cancel button to dismiss it
        locationPicker.navigationItem.leftBarButtonItem =
            UIBarButtonItem(title: "Отмена", style: .plain, target: self, action: #selector(closeLocationPicker))
        
        locationPicker.navigationItem.rightBarButtonItem =
            UIBarButtonItem(title: "Спутник", style: .plain, target: self, action: #selector(changeMapStyle))
        
        // set the wrapper
        let nc = UINavigationController(rootViewController: locationPicker)
        
        // show it modally
        self.present(nc, animated: true, completion: nil)
    }

**Comment by naveedmcs** [comment]
yes, title disappear first time when we change pin location on map using hold tapped. and also when scroll map.

**Comment by JoniVR** [comment]
Happens on the demo app too.
(iOS 13.3)

**Comment by LoopingLouieX** [comment]
Did anyone solved this already ?

**Comment by stephanboner** [comment]
No news here? I guess it only happens if you don't press "long enough". If you keep pressing after the pin is added and release after the animation, most of the time the title stays

**Comment by higalex** [comment]
I created a PR to fix this issue: https://github.com/almassapargali/LocationPicker/pull/76
