### ISSUE TITLE
Can't install pod

### ISSUE THREAD

**Issue by bharv410** [almassapargali/LocationPicker#7]
After doing pod install I am greeted with this error

Analyzing dependencies
[!] Unable to find a specification for `LocationPicker`

**Comment by uknowmeright** [comment]
+1 I got this issue as well.

**Comment by bharatkrishna** [comment]
The pod might not be added to cocoapods trunk. This needs to be fixed.

As a workaround, include the git path in your Podfile :

> pod 'LocationPicker', :git => 'https://github.com/almassapargali/LocationPicker.git'

**Comment by almassapargali** [comment]
Sorry guys, I'll take a look at this today later if I make any time.

**Comment by almassapargali** [comment]
Hey guys, sorry for taking so long. Pod is now on trunk. Also, I updated pod version, so it includes fixes implemented by @bharatkrishna. Thanks all :+1:
