### ISSUE TITLE
Not possible to localize "Select" button

### ISSUE THREAD

**Issue by teemu-rossi** [almassapargali/LocationPicker#9]
The button title for the "select location button" created in `LocationPickerViewController.selectLocationButton()` uses a hardcoded string. It would make sense to have this text customisable from outside to enable localisation and also using an app specific verb.

**Comment by almassapargali** [comment]
Sorry for delay, `selectButtonTitle` property has been added.

**Comment by teemu-rossi** [comment]
Thanks for the quick fix!
